name: Test Docker build

on: [pull_request]

jobs:
  build-amd64:
    name: Build amd64 image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Patch files
        uses: onlyutkarsh/patch-files-action@v1.0.1
        with:
          files: |
            telegram-bot-amazon/config.json
          patch-syntax: |
            = /version => "${{ github.run_number }}"
      - name: build amd64 image
        run: docker run --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v ~/.docker:/root/.docker -v "$(pwd)":/data homeassistant/amd64-builder -t telegram-bot-amazon --amd64 --test
  build-aarch64:
    name: Build aarch64 image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Patch files
        uses: onlyutkarsh/patch-files-action@v1.0.1
        with:
          files: |
            telegram-bot-amazon/config.json
          patch-syntax: |
            = /version => "${{ github.run_number }}"
      - name: build aarch64 image
        run: docker run --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v ~/.docker:/root/.docker -v "$(pwd)":/data homeassistant/amd64-builder -t telegram-bot-amazon --aarch64 --test
  build-armv7:
    name: Build armv7 image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Patch files
        uses: onlyutkarsh/patch-files-action@v1.0.1
        with:
          files: |
            telegram-bot-amazon/config.json
          patch-syntax: |
            = /version => "${{ github.run_number }}"
      - name: build armv7 image
        run: docker run --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v ~/.docker:/root/.docker -v "$(pwd)":/data homeassistant/amd64-builder -t telegram-bot-amazon --armv7 --test
  build-armhf:
    name: Build armhf image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Patch files
        uses: onlyutkarsh/patch-files-action@v1.0.1
        with:
          files: |
            telegram-bot-amazon/config.json
          patch-syntax: |
            = /version => "${{ github.run_number }}"
      - name: build armhf image
        run: docker run --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v ~/.docker:/root/.docker -v "$(pwd)":/data homeassistant/amd64-builder -t telegram-bot-amazon --armhf --test
  build-i386:
    name: Build i386 image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Patch files
        uses: onlyutkarsh/patch-files-action@v1.0.1
        with:
          files: |
            telegram-bot-amazon/config.json
          patch-syntax: |
            = /version => "${{ github.run_number }}"
      - name: build i386 image
        run: docker run --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v ~/.docker:/root/.docker -v "$(pwd)":/data homeassistant/amd64-builder -t telegram-bot-amazon --i386 --test
